/*
 * File: FEMhub.ModuleBasicWindow.ui.js
 * Date: Sun Dec 19 2010 21:37:15 GMT-0800 (PST)
 *
 * This file was generated by Ext Designer version xds-1.0.2.14.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('FEMhub');
FEMhub.ModuleBasicWindowUi = Ext.extend(Ext.Window, {
    title: 'Module Basic',
    width: 870,
    height: 580,
    layout: 'fit',
    boxMinHeight: 580,
    boxMinWidth: 880,
    initComponent: function() {
        this.items = [
            {
                xtype: 'tabpanel',
                activeTab: 0,
                title: '',
                ref: 'main_tabs',
                id: 'main_tabs',
                items: [
                    {
                        xtype: 'panel',
                        title: 'Geometry',
                        layout: 'fit',
                        tpl: '',
                        html: '',
                        ref: '../geometry_tab',
                        id: 'geometry_tab',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Operate on Nodes',
                                    ref: '../../../nodes_button'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Operate on Edges'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Operate on Subdomains'
                                }
                            ]
                        }
                    },
                    {
                        xtype: 'panel',
                        title: 'Model',
                        layout: 'border',
                        ref: '../model_tab',
                        id: 'model_tab',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Boundary Conditions',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Add new...',
                                                menu: {
                                                    xtype: 'menu',
                                                    items: [
                                                        {
                                                            xtype: 'menuitem',
                                                            text: 'Dirichlet',
                                                            menu: {
                                                                xtype: 'menu',
                                                                items: [
                                                                    {
                                                                        xtype: 'form',
                                                                        title: 'Enter Dirichlet Data',
                                                                        ref: '../../../../../../../../../dirichlet_bc_form',
                                                                        items: [
                                                                            {
                                                                                xtype: 'numberfield',
                                                                                name: 'Boundary Marker',
                                                                                value: '',
                                                                                allowDecimals: false,
                                                                                allowNegative: false,
                                                                                fieldLabel: 'Boundary Marker',
                                                                                anchor: '100%',
                                                                                ref: '../../../../../../../../../../dirichlet_bc_marker'
                                                                            },
                                                                            {
                                                                                xtype: 'numberfield',
                                                                                name: 'Solution Value',
                                                                                value: '',
                                                                                decimalPrecision: 6,
                                                                                fieldLabel: 'Solution Value',
                                                                                anchor: '100%',
                                                                                ref: '../../../../../../../../../../dirichlet_bc_value'
                                                                            },
                                                                            {
                                                                                xtype: 'button',
                                                                                text: 'Save',
                                                                                iconAlign: 'right',
                                                                                fieldLabel: '',
                                                                                labelSeparator: '',
                                                                                ref: '../../../../../../../../../../dirichlet_save_button'
                                                                            }
                                                                        ]
                                                                    }
                                                                ]
                                                            }
                                                        },
                                                        {
                                                            xtype: 'menuitem',
                                                            text: 'Neumann',
                                                            menu: {
                                                                xtype: 'menu',
                                                                items: [
                                                                    {
                                                                        xtype: 'form',
                                                                        title: 'Enter Neumann Data',
                                                                        items: [
                                                                            {
                                                                                xtype: 'numberfield',
                                                                                fieldLabel: 'Boundary Marker',
                                                                                anchor: '100%',
                                                                                name: 'Boundary Marker',
                                                                                allowDecimals: false,
                                                                                allowNegative: false,
                                                                                ref: '../../../../../../../../../../neumann_bc_marker'
                                                                            },
                                                                            {
                                                                                xtype: 'numberfield',
                                                                                decimalPrecision: 6,
                                                                                name: 'Solution Derivative',
                                                                                fieldLabel: 'Solution Derivative',
                                                                                ref: '../../../../../../../../../../neumann_bc_value'
                                                                            },
                                                                            {
                                                                                xtype: 'button',
                                                                                text: 'Save',
                                                                                ref: '../../../../../../../../../../neumann_save_button'
                                                                            }
                                                                        ]
                                                                    }
                                                                ]
                                                            }
                                                        },
                                                        {
                                                            xtype: 'menuitem',
                                                            text: 'Newton',
                                                            menu: {
                                                                xtype: 'menu',
                                                                items: [
                                                                    {
                                                                        xtype: 'form',
                                                                        title: 'Enter Newton Data',
                                                                        items: [
                                                                            {
                                                                                xtype: 'numberfield',
                                                                                fieldLabel: 'Boundary Marker',
                                                                                anchor: '100%',
                                                                                name: 'Boundary Marker',
                                                                                allowDecimals: false,
                                                                                allowNegative: false,
                                                                                ref: '../../../../../../../../../../newton_bc_marker'
                                                                            },
                                                                            {
                                                                                xtype: 'numberfield',
                                                                                fieldLabel: 'Constant #1',
                                                                                anchor: '100%',
                                                                                name: 'Constant #1',
                                                                                ref: '../../../../../../../../../../newton_bc_value_1'
                                                                            },
                                                                            {
                                                                                xtype: 'numberfield',
                                                                                fieldLabel: 'Constant #2',
                                                                                anchor: '100%',
                                                                                name: 'Constant #2',
                                                                                ref: '../../../../../../../../../../newton_bc_value_2'
                                                                            },
                                                                            {
                                                                                xtype: 'button',
                                                                                text: 'Save',
                                                                                ref: '../../../../../../../../../../newton_save_button'
                                                                            }
                                                                        ]
                                                                    }
                                                                ]
                                                            }
                                                        }
                                                    ]
                                                }
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'All boundary conditions:'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Materials',
                                    menu: {
                                        xtype: 'menu',
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                text: 'Add new...'
                                            },
                                            {
                                                xtype: 'menuitem',
                                                text: 'All materials:'
                                            }
                                        ]
                                    }
                                },
                                {
                                    xtype: 'tbfill'
                                }
                            ]
                        },
                        items: [
                            {
                                xtype: 'panel',
                                region: 'center',
                                autoScroll: true
                            },
                            {
                                xtype: 'panel',
                                region: 'west',
                                width: 142,
                                autoScroll: true,
                                split: true,
                                ref: '../../model_parameters'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Computation',
                        width: 770,
                        layout: 'border',
                        ref: '../computation_tab',
                        id: 'computation_tab',
                        items: [
                            {
                                xtype: 'panel',
                                title: '',
                                layout: 'absolute',
                                padding: 10,
                                shadow: 'frame',
                                width: 180,
                                height: 358,
                                itemId: 'computation_setup',
                                region: 'west',
                                ref: '../../computation_setup',
                                id: 'computation_setup',
                                items: [
                                    {
                                        xtype: 'displayfield',
                                        value: '',
                                        height: 5,
                                        width: 100
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Mesh refinements:',
                                        height: 20,
                                        width: 100,
                                        x: 10,
                                        y: 22
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 0,
                                        x: 110,
                                        y: 20,
                                        width: 50,
                                        height: 20,
                                        maxValue: 10,
                                        allowDecimals: false,
                                        allowNegative: false,
                                        ref: '../../../Init_ref_num',
                                        id: 'Init_ref_num'
                                    },
                                    {
                                        xtype: 'displayfield',
                                        value: 'Polynomial degree:',
                                        height: 20,
                                        width: 100,
                                        x: 10,
                                        y: 62
                                    },
                                    {
                                        xtype: 'numberfield',
                                        value: 4,
                                        x: 110,
                                        y: 60,
                                        width: 50,
                                        height: 20,
                                        allowNegative: false,
                                        allowDecimals: false,
                                        maxValue: 9,
                                        minValue: 1,
                                        ref: '../../../Init_p',
                                        id: 'Init_p'
                                    },
                                    {
                                        xtype: 'fieldset',
                                        title: 'Matrix solver',
                                        height: 180,
                                        width: 150,
                                        layout: 'auto',
                                        itemId: 'ms_field_set',
                                        x: 10,
                                        y: 100,
                                        id: 'ms_field_set',
                                        items: [
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'Amesos',
                                                inputValue: 'amesos',
                                                value: 'amesos',
                                                name: 'ms_radio_group',
                                                itemId: 'ms_radio_1',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_1'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'AztecOO',
                                                name: 'ms_radio_group',
                                                value: 'aztecoo',
                                                itemId: 'ms_radio_2',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_2'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'MUMPS',
                                                name: 'ms_radio_group',
                                                value: 'mumps',
                                                itemId: 'ms_radio_3',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_3'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'Pardiso',
                                                name: 'ms_radio_group',
                                                value: 'pardiso',
                                                itemId: 'ms_radio_4',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_4'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'PETSc',
                                                name: 'ms_radio_group',
                                                value: 'petsc',
                                                itemId: 'ms_radio_5',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_5'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'SuperLU',
                                                name: 'ms_radio_group',
                                                value: 'superlu',
                                                itemId: 'ms_radio_6',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_6'
                                            },
                                            {
                                                xtype: 'radio',
                                                boxLabel: 'UMFpack',
                                                checked: true,
                                                name: 'ms_radio_group',
                                                value: 'umfpack',
                                                itemId: 'ms_radio_7',
                                                ref: '../../../../Matrix_solver',
                                                id: 'ms_radio_7'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'button',
                                        text: 'Calculate',
                                        iconCls: '',
                                        cls: '',
                                        iconAlign: 'bottom',
                                        x: 110,
                                        y: 310,
                                        ref: '../../../calculate_button'
                                    }
                                ]
                            },
                            {
                                xtype: 'container',
                                region: 'center',
                                width: 100,
                                layout: 'border',
                                items: [
                                    {
                                        xtype: 'panel',
                                        title: '',
                                        layout: 'fit',
                                        height: 390,
                                        width: 100,
                                        itemId: 'computation_result',
                                        autoScroll: true,
                                        padding: 10,
                                        region: 'center',
                                        ref: '../../../computation_result',
                                        id: 'computation_result'
                                    },
                                    {
                                        xtype: 'panel',
                                        title: '',
                                        height: 110,
                                        layout: 'absolute',
                                        width: 100,
                                        shim: false,
                                        itemId: 'computation_log',
                                        autoScroll: true,
                                        padding: 10,
                                        region: 'south',
                                        ref: '../../../computation_log',
                                        id: 'computation_log'
                                    }
                                ]
                            }
                        ],
                        bbar: {
                            xtype: 'toolbar',
                            height: 25,
                            buttonAlign: 'center',
                            id: 'status_bar'
                        }
                    },
                    {
                        xtype: 'panel',
                        title: 'Postprocessing',
                        layout: 'fit',
                        ref: '../postprocessing_tab',
                        id: 'postprocessing_tab',
                        tbar: {
                            xtype: 'toolbar',
                            items: [
                                {
                                    xtype: 'button',
                                    text: 'Point Values'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Line Integrals'
                                },
                                {
                                    xtype: 'tbseparator'
                                },
                                {
                                    xtype: 'button',
                                    text: 'Volume Integrals'
                                }
                            ]
                        },
                        items: [
                            {
                                xtype: 'panel',
                                title: '',
                                layout: 'fit',
                                autoScroll: true,
                                ref: '../../postprocessing_panel'
                            }
                        ]
                    },
                    {
                        xtype: 'panel',
                        title: 'Help',
                        html: '',
                        ref: '../help_tab'
                    }
                ]
            }
        ];
        FEMhub.ModuleBasicWindowUi.superclass.initComponent.call(this);
    }
});

